### ISSUE TITLE
No way to escape the script

### ISSUE THREAD

**Issue by abhaseen** [rjayroso/haystack-link-checker#2]
There is currently no way to stop the script once it starts, this is not ideal since sometimes people can be running long lists and they may want to cut out of it ahead of completion of the script.

**Comment by rjayroso** [comment]
Thanks for pointing it out. I also noticed this in testing so I did a bit of research and it is because of my bare 'except' statement. To fix this I explicitly stated that if there is a KeyboardInterrupt (i.e. the user presses Ctrl+C) then it will perform sys.exit() and stop the script. In the future I would like to mess around and fix the bare except but for now this is my solution.
