### ISSUE TITLE
Double Arguments 

### ISSUE THREAD

**Issue by NesaByte** [rjayroso/haystack-link-checker#3]
[ ] Typing in -v -h, displays the version but disregards the -h argument. 
[ ] Typing in -h -v, displays the help but disregards the -v argument. 

Maybe you can enable 2 of these arguments or print an error statement saying that there are "too many command arguments."

**Comment by rjayroso** [comment]
Thank you for letting me know. At first I wanted this to be intentional - that it would only register the first valid argument that it received, but after more thought I decided that I would take your advice and make it clear that if there are two valid arguments I would just print a "too many command arguments" message.
