### ISSUE TITLE
Help message issue

### ISSUE THREAD

**Issue by sonechca** [rjayroso/haystack-link-checker#4]
![helpIssue](https://user-images.githubusercontent.com/50645765/94327784-3ac0de00-ff7b-11ea-8c1a-db97991fe4f6.png)

Have a help message issue
When I print a help message, the message print the whole code in the print()

I recommend using """ """ to print multiple line
https://stackoverflow.com/questions/34980251/how-to-print-multiple-lines-of-text-with-python

**Comment by rjayroso** [comment]
Thank you for the heads up! I couldn't use the triple quote for this multi line message in this case because I also used .format(), which using both together makes for unnecessarily long and hard to read/modify code. Anyways, I switched from using commas (',') and newline ('/n') to just separate individual print statements, which in my testing fixed this issue.
